security:
    password_hashers:
        App\Entity\Student:
            algorithm: auto
        App\Entity\Professor:
            algorithm: auto
    
    providers:
        student_provider:
            entity:
                class: App\Entity\Student
                property: Email
        professor_provider:
            entity:
                class: App\Entity\Professor
                property: Email
        all_users:
            chain:
                providers: ['student_provider', 'professor_provider']
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/course, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/student, roles: ROLE_STUDENT }
        - { path: ^/professor, roles: ROLE_PROFESSOR }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER